### ISSUE TITLE
Unsafe function .write()

### ISSUE THREAD

**Issue by frumentius** [jbialobr/JsQRScanner#12]
Hi, I Notice in jsqrscanner.nocache.js on line 4, you are using a .write() function. So this unsafe function is blocked by my App's Content Security Policy (CSP), However, even though it is blocked it the plugins still works fine in chrome for android, but the problem arise in safari for iOs. So the plugins only works in safari iOs, if I allow 'unsafe-inline' and 'unsave-eval' in my CSP, which is not a good security practice.

So can you update your plugin code, please, to replace the .write() function with the saver one.

**Comment by jbialobr** [comment]
This piece of code is generated by GWT compiler. I do not plan to patch it here. Consider reporting this issue to the [GWT project](http://www.gwtproject.org/lifeofanissue.html).
