### ISSUE TITLE
Sending results of QR read to GET request

### ISSUE THREAD

**Issue by martyndix** [jbialobr/JsQRScanner#17]
Hi,
Sorry if this is the wrong place to post this but how can I send the read value as a GET to a php page please? Upon reading a QR, I need it sending without the user leaving the scanning page.
Thanks in advance for any assistance anyone can give.

**Comment by jbialobr** [comment]
Indeed it is a wrong place fot this question. Try seeking http://stackoverflow.com for a simillar question.
