### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Adrianotiger** [jbialobr/JsQRScanner#2]
Hi,
I want firstly say: "thank you really much for this 'library'!"
Not only the code is really but incredible really fast, the code is also really stable and reliable!
Searching on Google I find always webcodecamjs, but your code is 10000 times better!
I can scan a QR code also when the code is not centered and also if is is in 10% of the screen, incredible (I wasn't able to do that with webcodecamjs).

What I miss is some documentation about the functions.
For example: stopScanning() to stop the scan, resumeScanning() to resume the scan - I found them but was hard. Sometimes it is also nice to stop the scan and start it again so that we don't need to leave the webpage (because every time the page ask to access the cam again).

Thank you again for this script!

**Comment by jbialobr** [comment]
>I want firstly say: "thank you really much for this 'library'!"

The pleasure is mine.

I updated the readme file. Let me know if something is unclear.
