### ISSUE TITLE
Ajax calls do not work

### ISSUE THREAD

**Issue by przemyslaws** [jbialobr/JsQRScanner#20]
Hey,
great work! amazing job with this scanner, but i have one problem. The function called after the QR is scanned, for some reason do not trigger ajax calls. No errors, it would do other stuff but not ajax.

Example:
```
function onQRCodeScanned(content)
{
$.ajax({
method: "POST",
url: "api.php?action=scan",
data: {id: 1, con: content}
})
.done(function(msg) {
console.log(msg);
})
.fail(function(msg) {
console.log(msg);
})
.always(function(msg) {
console.log(msg);
});
}
```

**Comment by aml-quiet-loud** [comment]
How did you fix that ?
