### ISSUE TITLE
Can't figure out how to use .removeFrom

### ISSUE THREAD

**Issue by predictcare** [jbialobr/JsQRScanner#27]
Hi, i'm using the quick version to scan a qr code.

`var scannerParentElement = document.getElementById("scanner");
          if(scannerParentElement)
          {
              //append the jbScanner to an existing DOM element
            jbScanner.appendTo(scannerParentElement);
        }
            `
And it works fine.
But when i need to remove the element, with :
`var scannerParentElement = document.getElementById("scanner");
          if(scannerParentElement)
          {
              //append the jbScanner to an existing DOM element
            jbScanner.removeFrom(scannerParentElement);
        }`
I have an error about DOM and Node : 

> Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is > not a child of this node.

Thanks

**Comment by webaff** [comment]
Same problem here...

**Comment by jbialobr** [comment]
It works fine. Please provide a reproducible code.

**Comment by webaff** [comment]
> It works fine. Please provide a reproducible code.

Yes, you are right. It was my crappy scripting... sorry.
