### ISSUE TITLE
Not working on IOS

### ISSUE THREAD

**Issue by ram1shinde** [jbialobr/JsQRScanner#3]
Hi ,

Code not working on IOS mobile browser.

Please help.

Thanks,
Rahul

**Comment by jbialobr** [comment]
I am sorry, but I don't have an IOS device.

**Comment by ram1shinde** [comment]
Okk NP,

Thanks :)

**Comment by tbassett44** [comment]
iOS does not support webRTC so you have to use a polyfill of sorts.  I just started playing with this today and am able to get the video feed to show up in a canvas element inside of a html app, but i have not yet got it to correctly scan a qr code...or flip to the backside camera...will try to hack some of it together....

Here is the plugin I am using for iOS apps
https://www.npmjs.com/package/cordova-plugin-webrtc

**Comment by javismiles** [comment]
iOS 11 now supports WebRtc so it should work ok on iOS, will test this today

**Comment by agusbrand** [comment]
Not working in iOS 11 :(  were you able to find a solution?

**Comment by gbeltran13** [comment]
were you able to find a solution? not work in IOS, thanks

**Comment by kucukkanat** [comment]
I tried inspecting the demo on iOS safari on my mac, didn't come across any errors on console.

**Comment by JoOtNlanfall** [comment]
Works like a charm on android, any news about ios?

**Comment by Flixbox** [comment]
I have an iOS 12 device right here and it doesn't work. Safari prompts for camera access and a black box loads. Same for all other web QR scanners.

**Comment by jbialobr** [comment]
Do you see any errors when you open the safari dev tools and reload the page?

**Comment by Flixbox** [comment]
I'm using an iPhone and I don't own a mac, so I'd be unable to show the console. Right?

**Comment by Flixbox** [comment]
However, I can circumvent this by using a try/catch construct. I'm currently using Instascan, but since JsQRScanner is better supported, in active development and the dev actually answers questions, I'll try using this one instead. I'll come back to you once I've switched.

**Comment by Flixbox** [comment]
Alright, I have set up the QR scanner on my website and it's working perfectly on Android. However, it's still just showing a black box on Safari. How would I debug that? I don't have a mac to connect to. There is no way to show the console on Safari. Promise rejections and errors are quite hard to echo if I don't have access to the promise object.

Note that I could quite easily show text on the iPhone with my setResult() function, because it shows text inside of a div. I just have no way of actually getting an error message within my JS.

Here's my code: 

```javascript
/**
 * Sets up the QR scanner.
 * this function will be called when JsQRScanner is ready to use
 * @see https://github.com/jbialobr/JsQRScanner
 */
function JsQRScannerReady() {
    try {
        //create a new scanner passing to it a callback function that will be invoked when
        //the scanner succesfully scan a QR code
        var jbScanner = new JsQRScanner(scanEvent);
        setResult("Constructed JsQRScanner object.");
        //reduce the size of analyzed images to increase performance on mobile devices
        jbScanner.setSnapImageMaxSize(300);
        setResult("setSnapImageMaxSize completed.");
        var scannerParentElement = document.getElementById("videoBoundingBox");
        if (scannerParentElement) {
            //append the jbScanner to an existing DOM element
            jbScanner.appendTo(scannerParentElement);
            setResult("Appended jbScanner to div.");
        }   
    } catch (e) {
        setResult("Caught exception in the camera initialisation.");
        setResult(e.message);
    }
    setResult("initialisation complete.");
}
```

----------------------------------
Addendum: I've added some more logging to my code. Every single line in this function is being executed without throwing any errors, and every line of setResult() shows up in my div.

**Comment by jbialobr** [comment]
I added exception reporting as a scanned code. I uploaded changed scripts to jsPretty folder. You can also try the live demo (which I also updated) https://jbialobr.github.io/JsQRScanner/ to see if any errors are shown.

**Comment by Flixbox** [comment]
Nope, no error messages here. And yes, I did delete all browsing data before accessing the website. 

[Here's the commit](https://github.com/jbialobr/JsQRScanner/commit/46641ad9a2deba9b73e83848c8d2abe4274ed375)

I'll check your code on the exceptions. Maybe I can figure something out.

Screenshots:

![image](https://user-images.githubusercontent.com/14835021/45822609-2393e980-bcec-11e8-9b0d-7ec9b4ef177d.png)
![image](https://user-images.githubusercontent.com/14835021/45822627-30184200-bcec-11e8-8bbc-1fc8241592b2.png)

**Comment by Flixbox** [comment]
I've updated all files and I've changed a bit of my code, however I can't figure out how your reportError method works. Could you tell me how I can get your error messages?

```javascript
/**
 * Sets up the QR scanner.
 * this function will be called when JsQRScanner is ready to use
 * @see https://github.com/jbialobr/JsQRScanner
 */
function JsQRScannerReady() {
    try {
        //create a new scanner passing to it a callback function that will be invoked when
        //the scanner succesfully scan a QR code
        var jbScanner = new JsQRScanner(scanEvent);
        setResult("Constructed JsQRScanner object. v2");
        //reduce the size of analyzed images to increase performance on mobile devices
        jbScanner.setSnapImageMaxSize(300);
        // setResult("setSnapImageMaxSize completed.");
        var scannerParentElement = document.getElementById("videoBoundingBox");
        if (scannerParentElement) {
            jbScanner.reportError = reportError;
            //append the jbScanner to an existing DOM element
            jbScanner.appendTo(scannerParentElement);
            setResult("Appended jbScanner to div.");
        }   
    } catch (e) {
        setResult("Caught exception in the camera initialisation.");
        setResult(e.message);
    }
    setResult("initialisation complete.");
}

function reportError(e, message) {
    setResult(e);
    setResult(message);
}
```

**Comment by jbialobr** [comment]
On Android I get an error when I don't grant the access to use the webcam.

**Comment by Flixbox** [comment]
Well, I'm not getting any errors on iOS, so the problem can't be with the access. Do you have any other options to figure out this bug? I mean, http://qrcodescan.in can do it on Safari, but their documentation is much, much worse.

**Comment by jbialobr** [comment]
That is a great news. If they can do it, that means it is doable. I took a look at that repo and I think it might be due to the playsinline attribute not being set. I uploaded a new version. Can you try it? https://jbialobr.github.io/JsQRScanner/

**Comment by Flixbox** [comment]
Thank you for your assistance so far. The iPhone is safe and sound in my office, so I'll try it tomorrow morning.

**Comment by Flixbox** [comment]
It's working perfectly, just like on Android!

**Comment by jbialobr** [comment]
Happy to hear it. I will upload the minified version then.

**Comment by jbialobr** [comment]
Thank you @RubbelDieKatz for your help in resolving this issue.

**Comment by sedll7809** [comment]
Thank you for your
