### ISSUE TITLE
Front facing camera

### ISSUE THREAD

**Issue by bjwelker** [jbialobr/JsQRScanner#34]
Is it possible to switch to the Front facing camera i only get back facing....

**Comment by jbialobr** [comment]
You can provide a video stream by yourself (see https://github.com/jbialobr/JsQRScanner -> Providing a video stream in a custom way) with the constraint: video: { facingMode: "user" } (see https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia)
