### ISSUE TITLE
onQRCodeScanned repeatedly called

### ISSUE THREAD

**Issue by javismiles** [jbialobr/JsQRScanner#4]
when a code is found onQRCodeScanned is called,
and then i do an action

but onQRCodeScanned keeps getting call after a detection, infinitely,
even if i point phone in another direction,

it should be called once, and just once after a detection, any help?

**Comment by jbialobr** [comment]
I added scanned texts history to the live demo https://jsqrscanner.appspot.com and it works as expected.
While the camera is pointed to somewhere else the history stops being populated with scanned texts.

I uploaded the script compiled to the pretty format. Perhaps you will be able to debug in devtools.
https://github.com/jbialobr/JsQRScanner/tree/master/war/jsPretty

**Comment by javismiles** [comment]
Hey, thanks a lot for the super quick reply and congratulations for your project :)
I saw the new version, that´s actually the problem for me, if you keep the code in the same place , it keeps scanning it and triggering the onQRCodeScanned , and the history field keeps getting populated with the very same code. In any case I found the solution, calling stopScanning and then  a timeout and resuming scanning again, helps to provide a pause before the scanner gets active again

`jbScanner.stopScanning();
			setTimeout(function(){ detcode="";jbScanner.resumeScanning(); }, 3000);`

**Comment by jbialobr** [comment]
The scanner can not know if you point to the same qr code or to another that by accident encodes the same text. Hence it is designed to keep scanning. The consumer library can stop scanning like you did or can compare the consecutive texts in order to trigger an action only if the scanned text differs from the previous one.

**Comment by DevinSmith69** [comment]
> 
> 
> Hey, thanks a lot for the super quick reply and congratulations for your project :)
> I saw the new version, that´s actually the problem for me, if you keep the code in the same place , it keeps scanning it and triggering the onQRCodeScanned , and the history field keeps getting populated with the very same code. In any case I found the solution, calling stopScanning and then a timeout and resuming scanning again, helps to provide a pause before the scanner gets active again
> 
> `jbScanner.stopScanning(); setTimeout(function(){ detcode="";jbScanner.resumeScanning(); }, 3000);`

Can you please advise where you placed this? i see jbscanner in the HTML file which loops back to the onQRCodeScanned however no matter where I place it it keeps scanning, I have also tried if (scannedText != Null) { onQRCodeScanned.stopScanning(); } this stops writing to the history but does not physically stop the scan when it finds a result
