### ISSUE TITLE
Scanner Doesnt Work On Chrome

### ISSUE THREAD

**Issue by Shwabster** [jbialobr/JsQRScanner#43]
I have implemented the library successfully and it is all working as expected on Firefox (Windows - Using Localhost HTTP and deployed HTTPS) and Safari (iOS - Deployed HTTPS).

However it does not work at all on Chrome, either on Windows or Android and neither via Localhost HTTP or deployed HTTPS.

The demo page doesn't work either in Chrome (HTTPS).

https://jbialobr.github.io/JsQRScanner/

![image](https://user-images.githubusercontent.com/72385797/98375660-51f2f100-203a-11eb-9ebf-ffabea43df06.png)

**Comment by flavio-schoute** [comment]
On my Chrome browser it works, maybe reload the page or enable JS?

**Comment by Shwabster** [comment]
JavaScript is enabled and reloading does not work.

Are you able to post a screenshot of it working? What version of Chrome are you using?

I can still reproduce, the demo project does not work on Chrome.

**Comment by genesisyau** [comment]
> JavaScript is enabled and reloading does not work.
> 
> Are you able to post a screenshot of it working? What version of Chrome are you using?
> 
> I can still reproduce, the demo project does not work on Chrome.

I think it might have something to do with the device's camera. As I mentioned on issue #44 , it is working on Chrome. My version is 87.0.4280.141 on both desktop and mobile.

**Comment by genesisyau** [comment]
Also, make sure that nothing else is using the camera. For example, on chrome, only one tab should be able to use the camera. If I open two tabs that need the camera, it won't run in one of them.

**Comment by Shwabster** [comment]
Updated Chrome to version 88.0.4324.104 and the demo is now working as expected along with my project.
