### ISSUE TITLE
Support on browsers

### ISSUE THREAD

**Issue by javismiles** [jbialobr/JsQRScanner#5]
Hi, 
I have tested your library on android and it works great, also on PC, will test on Safari today,
but I tested on Microsoft Edge browser now and it didnt work, however Edge supports WebRtc
https://caniuse.com/#search=webrtc

why is it not working on Edge? on which browsers has this been tested?
all best

**Comment by jbialobr** [comment]
What version of edge did you test against? It works well for me.
![gitext](https://user-images.githubusercontent.com/1003909/32435296-d17cb2e0-c2e0-11e7-9fa7-708988f12728.png)

**Comment by javismiles** [comment]
It also fails on firefox by the way, just tested, let me check edge version for you, but I have latest windows 10 with updates installed,

**Comment by javismiles** [comment]
will post screens, a sec

**Comment by javismiles** [comment]
here, edge is  Microsoft Edge 40.15063.674.0
and Microsoft EdgeHTML 15.15063

**Comment by javismiles** [comment]
we have same version

**Comment by javismiles** [comment]
executing https://jsqrscanner.appspot.com/ on my edge, same version,  shows no errors on console,  but the camera just wont activate,it asks for permission,  i give permission and it just wont activate

**Comment by javismiles** [comment]
exact same problem on firefox, both on firefox and edge, app asks for permission to use camera, I accept and then nothing happens, camera doesnt activate

**Comment by javismiles** [comment]
on firefox, the console will show 
"Invalid URI. Load of media resource  failed."
I wonder if the webrtc code is outdated or something

**Comment by javismiles** [comment]
"Invalid URI. Load of media resource  failed."
the activation of camera fails on firefox and edge, despite accepting the permission request

**Comment by javismiles** [comment]
I have some ideas, I tested the demo here
https://blog.niap3d.com/fr/4,10,news-76-jsQRScan-scanner-un-code-QR-en-Javascript.html
and it has same problem, and in firefox gives the error:
"navigator.mozGetUserMedia has been replaced by navigator.mediaDevices.getUserMedia , Error mediaDevices : NotReadableError: Failed to allocate videosource"

I think both your code and that one may have the same issue, getusermedia code needs to be updated because part of it became deprecated recently and that's why on firefox and edge both are failing to show the camera (android works well)

mediadevices should be the way now for all browsers, using the previous getusermedia route is causing it to fail on firefox and edge

**Comment by javismiles** [comment]
yep this is confirmed
I changed the code and now it works, the code has  to be changed to use only mediaDevices, then  it will work in all browsers 

`	try {
 navigator.mediaDevices.getUserMedia(constraints).then(function success(stream) {
	qrStream = stream; 
	qrVideo.srcObject = stream;
	qrVideo.play(); 
 });
}
	
catch(err) {console.log("Error mediaDevices : " + err);
  }	`

**Comment by javismiles** [comment]
I would modify your code also but your code is all encoded in a way that is very hard to change

**Comment by javismiles** [comment]
if its working for you on edge then it means you have different code in the mediadevices area, maybe you could update the code here in the repository? thanks a lot :)

**Comment by jbialobr** [comment]
It uses mediaDevices if defined:
https://github.com/jbialobr/gwt-qrscanner/blob/b0495dab8457cd551ff81bf9bcb8be1cd3bdffd3/core/src/main/java/com/google/zxing/web/ScannerWidget.java#L178
You can submit your patch there.

**Comment by javismiles** [comment]
I did tests on iOS , both your code and the other one dont work well . Again the problem is the same. The getusermedia code has to be updated in both libraries, it is not up to date

**Comment by javismiles** [comment]
hey, thank you for the reply,
what do you mean by " if defined" ? if defined where and how?

what I can confirm is that it fails on iOS (just tested), firefox and edge because of mediaDevices issues

and you are right, the mediadevices code is there, not sure why it's not being used 

thank you

**Comment by javismiles** [comment]
in any case in the meantime i modified the code of
https://blog.niap3d.com/fr/24,10,news-76-jsQRScan-scanner-un-code-QR-en-Javascript.html
which is very easy to change, and now it works on iOS,   i just made mediaDevices a straight path
`var constraints = {
    audio: false,
    video: {
      facingMode: "environment"
    }
  };
		
		
try {
 navigator.mediaDevices.getUserMedia(constraints).then(function success(stream) {
	qrStream = stream; 
	qrVideo.srcObject = stream;
	qrVideo.play(); 
 });
}`
