### ISSUE TITLE
Uncaught (in promise) DOMException: Only secure origins are allowed

### ISSUE THREAD

**Issue by jkimilu** [jbialobr/JsQRScanner#6]
First of all thanks for this great plugin. i have managed to set it up and it is working but only on local host. When i try to test on the public ip address i get below error

Uncaught (in promise) DOMException: Only secure origins are allowed -Promise rejected (async)

Kindly assist..

Regards
Joel Kimilu

**Comment by jbialobr** [comment]
It is your web browser that disallows using your web cam on sites that are not served from https.
There is nothing I can help. See this SO answer for chrome https://stackoverflow.com/questions/34197653/getusermedia-in-chrome-47-without-using-https
I believe other browsers have the same security policy in this area.

**Comment by jkimilu** [comment]
Thanks for your response. I already figured. Otherwise it works  as per
your instructions.

Thanks again.

Regards
Joel Kimilu

On Jan 28, 2018 3:12 PM, "Janusz Białobrzewski" <notifications@github.com>
wrote:

It is your web browser that disallows using your web cam on sites that are
not served from https.
There is nothing I can help. See this SO answer for chrome
https://stackoverflow.com/questions/34197653/getusermedia-in-chrome-47-
without-using-https
I believe other browsers have the same security policy int this area.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jbialobr/JsQRScanner/issues/6#issuecomment-361058265>,
or mute the thread
