### ISSUE TITLE
QQ browser does not use the rear camera

### ISSUE THREAD

**Issue by sedll7809** [jbialobr/JsQRScanner#8]
I run this demo in  android chrome  success，but i run in ios Safari ，video can not display 。this program can run in ios Safari ？

How do I listen for the scan results interface，thanks

**Comment by jbialobr** [comment]
Please read https://github.com/jbialobr/JsQRScanner/issues/3 to see how @Katzenrubbler was able to provide some details of how it is not working. Perhaps you find it useful and you will be able to provide more  details.

**Comment by sedll7809** [comment]
Thank you very much ，I have already run in ios 12.0.1

**Comment by sedll7809** [comment]
hi jbialobr:
When I run in qq browser ,it only display Front camera,When i run in chrome  it's ok. how do i  run in qq browser  call The rear camera

**Comment by jbialobr** [comment]
The scanner requests the `environment` camera. I have no idea why the qq browser does not respect it.
Read https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia and try to get a video element showing a stream from the rear camera. If you succeed I can include the solution into the scanner.

**Comment by sedll7809** [comment]
hi jbialobr
I have test this can open rear camera for qq browser，but i  do not know how to modify your program，
You can add the following paragraph in your program, if it is qq browser，thanks
 var exArray = [];
        navigator.mediaDevices.enumerateDevices()
        .then(function(devices) {
            devices.forEach(function(device) {
                if (device.kind === 'videoinput') {
                    exArray.push(device.deviceId)
                }
            });
            navigator.getUserMedia ? navigator.getUserMedia({
                video: {
                    'optional': [{
                    'sourceId': exArray[1]//this qq browser can open  rear camera
}]
                    }
                }, e, b) : console.log("Native web camera streaming (getUserMedia) not supported in this browser.");
                qrcode.callback = a;
            })

**Comment by sedll7809** [comment]
(function(d) {
    d.fn.html5_qrcode = function(a, c, b) {
        var e = this.height()
          , g = this.width();
        null == e && (e = 250);
        null == g && (g = 300);
        var f = '<canvas id="qr-canvas" width="' + (g - 2) + 'px" height="' + (e - 2) + 'px" style="display:none;"></canvas>';
        this.append('<video id="html5_qrcode_video" width="' + g + 'px" height="' + e + 'px"></video>');
        this.append(f);
        var h = d("#html5_qrcode_video").get(0), j;
        d("#qr-canvas").each(function(a, b) {
            j = b.getContext("2d")
        });
        var k = function() {
            if (localMediaStream) {
                j.drawImage(h, 0, 0, 307, 250);
                try {
                    qrcode.decode()
                } catch (a) {
                    c(a)
                }
                setTimeout(k, 500)
            } else
                setTimeout(svan, 500)
        };
        window.URL = window.URL || window.webkitURL || window.mozURL || window.msURL;
        navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia || navigator.msGetUserMedia;
        e = function(a) {
            h.src = window.URL && window.URL.createObjectURL(a) || a;
            localMediaStream = a;
            h.play();
            setTimeout(k, 1E3)
        }
        ;
        var exArray = [];
        navigator.mediaDevices.enumerateDevices()
        .then(function(devices) {
            devices.forEach(function(device) {
                if (device.kind === 'videoinput') {
                    exArray.push(device.deviceId)
                }
            });
            navigator.getUserMedia ? navigator.getUserMedia({
                video: {
                    'optional': [{
                    'sourceId': exArray[1]//this qq browser can open  rear camera
}]
                    }
                }, e, b) : console.log("Native web camera streaming (getUserMedia) not supported in this browser.");
                qrcode.callback = a;
            })
    }
}
)(jQuery);

**Comment by sedll7809** [comment]
(function(d) {
    d.fn.html5_qrcode = function(a, c, b) {
        var e = this.height()
          , g = this.width();
        null == e && (e = 250);
        null == g && (g = 300);
        var f = '<canvas id="qr-canvas" width="' + (g - 2) + 'px" height="' + (e - 2) + 'px" style="display:none;"></canvas>';
        this.append('<video id="html5_qrcode_video" width="' + g + 'px" height="' + e + 'px"></video>');
        this.append(f);
        var h = d("#html5_qrcode_video").get(0), j;
        d("#qr-canvas").each(function(a, b) {
            j = b.getContext("2d")
        });
        var k = function() {
            if (localMediaStream) {
                j.drawImage(h, 0, 0, 307, 250);
                try {
                    qrcode.decode()
                } catch (a) {
                    c(a)
                }
                setTimeout(k, 500)
            } else
                setTimeout(svan, 500)
        };
        window.URL = window.URL || window.webkitURL || window.mozURL || window.msURL;
        navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia || navigator.msGetUserMedia;
        e = function(a) {
            h.src = window.URL && window.URL.createObjectURL(a) || a;
            localMediaStream = a;
            h.play();
            setTimeout(k, 1E3)
        }
        ;
        var exArray = [];
        navigator.mediaDevices.enumerateDevices()
        .then(function(devices) {
            devices.forEach(function(device) {
                if (device.kind === 'videoinput') {
                    exArray.push(device.deviceId)
                }
            });
            navigator.getUserMedia ? navigator.getUserMedia({
                video: {
                    'optional': [{
                    'sourceId': exArray[1]//this qq browser can open  rear camera
}]
                    }
                }, e, b) : console.log("Native web camera streaming (getUserMedia) not supported in this browser.");
                qrcode.callback = a;
            })
    }
}
)(jQuery);

**Comment by jbialobr** [comment]
Thank you @sedll7809! I added the ability to provide video stream in a custom way. I updated the readme page with an example showing how to do this.

**Comment by sedll7809** [comment]
hi jbialobr
Thank you very much,Now I use two pages to open the camera, when I detect qq browser, jump to open the qq camera page, when I try to put on a page will report an error, but this has solved my problem, thank you。
