### ISSUE TITLE
Not working on Chrome iOS

### ISSUE THREAD

**Issue by chosten** [jbialobr/JsQRScanner#9]
Hello, `MediaStreamTrack.getSources` has been deprecated and is not working anymore on iOS.
I believe [this](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices) is the replacement. But it does not seem to work on iOS either
Any solution to this problem ?

**Comment by RogelioHIT** [comment]
hi, did you find the solution?, I'm having the same problem :/

**Comment by chosten** [comment]
No, I only got it working in Safari.

**Comment by jbialobr** [comment]
I removed MediaStreamTrack.getSources, but if it got into that if branch that means that your browser does not support MediaDevices as well. I left the fallback choosing any available webcam.
